spring:
  application:
    name: TelBot
  datasource:
    url: jdbc:postgresql://localhost:5432/category_bot
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

bot:
  username: category_newBot
  token: 7514418381:AAEJvKL5dwVQRUpXMF7PNcLwoBPDTDgOTRk